### ISSUE TITLE
Import OSM tags (for scoring purposes)

### ISSUE THREAD

**Issue by hkrishna** [pelias/openstreetmap#33]
Each point we import belongs to one of these [features](https://github.com/pelias/openstreetmap/blob/master/features.js#L1-L21). It would be nice if we used all the tags that each of these osm nodes contain and add it to the pelias model document. 

Obviously we need to change the [schema](https://github.com/pelias/schema) to add a field called ```tags``` thats a hash or an array of all tags. 

We could have another file ```weighted_tags.yml``` in a different repo where we can define what weight each tag value corresponds to.

```yml
   airport: 10
   railway: 10
   restaurant: 5
   tourism: 15
   ...
```
